import type { CategorySeedItem } from './types';

export const DEFAULT_CATEGORIES: CategorySeedItem[] = [
  {
    slug: 'women',
    name: 'Women',
    icon: '👗',
    displayOrder: 1,
    seoTitle: 'Women\'s Fashion Near You | ShowMyFIT',
    seoDescription: 'Shop women\'s clothing, dresses, kurtas, and accessories from local stores on ShowMyFIT.',
    keywords: ['women fashion', 'women clothing', 'dresses', 'kurtas'],
    subcategories: [
      { slug: 'tops-t-shirts', name: 'Tops & T-shirts' },
      { slug: 'dresses-kurtas', name: 'Dresses & Kurtas' },
      { slug: 'jeans-pants', name: 'Jeans & Pants' },
      { slug: 'sarees-ethnic-wear', name: 'Sarees & Ethnic Wear' },
      { slug: 'jackets-sweaters', name: 'Jackets & Sweaters' },
      { slug: 'innerwear-lingerie', name: 'Innerwear & Lingerie' },
      { slug: 'jewellery-accessories', name: 'Jewellery & Accessories' },
    ],
  },
  {
    slug: 'men',
    name: 'Men',
    icon: '👨',
    displayOrder: 2,
    seoTitle: 'Men\'s Fashion Near You | ShowMyFIT',
    seoDescription: 'Discover men\'s shirts, jeans, jackets, and accessories from nearby stores.',
    keywords: ['men fashion', 'men clothing', 'shirts', 'jeans'],
    subcategories: [
      { slug: 'shirts-t-shirts', name: 'Shirts & T-shirts' },
      { slug: 'jeans-trousers', name: 'Jeans & Trousers' },
      { slug: 'shorts-trackpants', name: 'Shorts & Trackpants' },
      { slug: 'jackets-hoodies', name: 'Jackets & Hoodies' },
      { slug: 'innerwear', name: 'Innerwear' },
      { slug: 'watches-accessories', name: 'Watches & Accessories' },
    ],
  },
  {
    slug: 'footwear',
    name: 'Footwear',
    icon: '👟',
    displayOrder: 3,
    seoTitle: 'Footwear & Shoes Near You | ShowMyFIT',
    seoDescription: 'Buy sneakers, formal shoes, sandals, and sports footwear from local sellers.',
    keywords: ['footwear', 'shoes', 'sneakers', 'sandals'],
    subcategories: [
      { slug: 'mens-footwear', name: "Men's Footwear" },
      { slug: 'womens-footwear', name: "Women's Footwear" },
      { slug: 'kids-footwear', name: 'Kids Footwear' },
      { slug: 'sandals-slippers', name: 'Sandals & Slippers' },
      { slug: 'sneakers-sports-shoes', name: 'Sneakers & Sports Shoes' },
      { slug: 'formal-shoes', name: 'Formal Shoes' },
      { slug: 'casual-shoes', name: 'Casual Shoes' },
    ],
  },
  {
    slug: 'jewellery',
    name: 'Jewellery',
    icon: '💍',
    displayOrder: 4,
    seoTitle: 'Jewellery Near You | ShowMyFIT',
    seoDescription: 'Shop earrings, necklaces, rings, and fashion jewellery from local stores.',
    keywords: ['jewellery', 'earrings', 'necklaces', 'rings'],
    subcategories: [
      { slug: 'gold-plated-jewellery', name: 'Gold-plated Jewellery' },
      { slug: 'silver-jewellery', name: 'Silver Jewellery' },
      { slug: 'artificial-jewellery', name: 'Artificial Jewellery' },
      { slug: 'earrings', name: 'Earrings' },
      { slug: 'necklaces', name: 'Necklaces' },
      { slug: 'bangles', name: 'Bangles' },
      { slug: 'rings', name: 'Rings' },
    ],
  },
  {
    slug: 'lingerie',
    name: 'Lingerie',
    icon: '👙',
    displayOrder: 5,
    seoTitle: 'Lingerie & Innerwear | ShowMyFIT',
    seoDescription: 'Find bras, nightwear, and lingerie from trusted local sellers.',
    keywords: ['lingerie', 'innerwear', 'nightwear'],
    subcategories: [
      { slug: 'bra', name: 'Bra' },
      { slug: 'panties', name: 'Panties' },
      { slug: 'lingerie-set', name: 'Lingerie Set' },
      { slug: 'nightwear', name: 'Nightwear' },
      { slug: 'shapewear', name: 'Shapewear' },
      { slug: 'sleepwear', name: 'Sleepwear' },
    ],
  },
  {
    slug: 'watches',
    name: 'Watches',
    icon: '⌚',
    displayOrder: 6,
    seoTitle: 'Watches Near You | ShowMyFIT',
    seoDescription: 'Shop analog, digital, and smartwatches from nearby stores.',
    keywords: ['watches', 'smartwatch', 'analog watch'],
    subcategories: [
      { slug: 'analog', name: 'Analog' },
      { slug: 'digital', name: 'Digital' },
      { slug: 'smartwatch', name: 'Smartwatch' },
      { slug: 'chronograph', name: 'Chronograph' },
      { slug: 'luxury', name: 'Luxury' },
      { slug: 'casual', name: 'Casual' },
    ],
  },
  {
    slug: 'gifting-guide',
    name: 'Gifting Guide',
    icon: '🎁',
    displayOrder: 7,
    seoTitle: 'Gift Ideas Near You | ShowMyFIT',
    seoDescription: 'Find birthday, wedding, and festival gifts from local shops.',
    keywords: ['gifts', 'gift ideas', 'birthday gifts'],
    subcategories: [
      { slug: 'birthday', name: 'Birthday' },
      { slug: 'anniversary', name: 'Anniversary' },
      { slug: 'wedding', name: 'Wedding' },
      { slug: 'festivals', name: 'Festivals' },
      { slug: 'corporate', name: 'Corporate' },
    ],
  },
  {
    slug: 'kids',
    name: 'Kids',
    icon: '👶',
    displayOrder: 8,
    seoTitle: 'Kids Products Near You | ShowMyFIT',
    seoDescription: 'Shop kids clothing, toys, and school supplies from local stores.',
    keywords: ['kids', 'children', 'baby clothes', 'toys'],
    subcategories: [
      { slug: 'baby-clothes', name: 'Baby Clothes' },
      { slug: 'toys', name: 'Toys' },
      { slug: 'school-supplies', name: 'School Supplies' },
      { slug: 'footwear', name: 'Footwear' },
      { slug: 'accessories', name: 'Accessories' },
    ],
  },
  {
    slug: 'home-lifestyle',
    name: 'Home & Lifestyle',
    icon: '🏠',
    displayOrder: 9,
    seoTitle: 'Home & Lifestyle Products | ShowMyFIT',
    seoDescription: 'Discover home decor, kitchen tools, and lifestyle products nearby.',
    keywords: ['home decor', 'kitchen', 'lifestyle'],
    subcategories: [
      { slug: 'kitchen-tools', name: 'Kitchen Tools' },
      { slug: 'home-decor', name: 'Home Decor' },
      { slug: 'bedsheets-curtains-towels', name: 'Bedsheets, Curtains & Towels' },
      { slug: 'cleaning-storage-items', name: 'Cleaning & Storage Items' },
    ],
  },
  {
    slug: 'accessories',
    name: 'Accessories',
    icon: '👜',
    displayOrder: 10,
    seoTitle: 'Fashion Accessories Near You | ShowMyFIT',
    seoDescription: 'Sunglasses, belts, wallets, and more from local sellers.',
    keywords: ['accessories', 'sunglasses', 'belts', 'wallets'],
    subcategories: [
      { slug: 'watches', name: 'Watches' },
      { slug: 'sunglasses', name: 'Sunglasses' },
      { slug: 'belts', name: 'Belts' },
      { slug: 'caps-hats', name: 'Caps & Hats' },
      { slug: 'wallets-purses', name: 'Wallets & Purses' },
    ],
  },
  {
    slug: 'beauty',
    name: 'Beauty by Tira',
    icon: '💄',
    displayOrder: 11,
    seoTitle: 'Beauty Products Near You | ShowMyFIT',
    seoDescription: 'Skincare, makeup, haircare, and fragrance from nearby beauty stores.',
    keywords: ['beauty', 'skincare', 'makeup', 'haircare'],
    subcategories: [
      { slug: 'skincare', name: 'Skincare' },
      { slug: 'makeup', name: 'Makeup' },
      { slug: 'haircare', name: 'Haircare' },
      { slug: 'fragrance', name: 'Fragrance' },
      { slug: 'bath-body', name: 'Bath & Body' },
      { slug: 'mens-grooming', name: "Men's Grooming" },
      { slug: 'tools-brushes', name: 'Tools & Brushes' },
    ],
  },
  {
    slug: 'sportswear',
    name: 'Sportswear',
    icon: '⚽',
    displayOrder: 12,
    seoTitle: 'Sportswear & Activewear | ShowMyFIT',
    seoDescription: 'Activewear, tracksuits, and sports shoes from local fitness stores.',
    keywords: ['sportswear', 'activewear', 'gym wear', 'sports'],
    subcategories: [
      { slug: 'activewear-tops', name: 'Activewear Tops' },
      { slug: 'bottoms', name: 'Bottoms' },
      { slug: 'tracksuits', name: 'Tracksuits' },
      { slug: 'swimwear', name: 'Swimwear' },
      { slug: 'innerwear', name: 'Innerwear' },
      { slug: 'shoes', name: 'Shoes' },
      { slug: 'accessories', name: 'Accessories' },
    ],
  },
];
